import { EventEmitter, OnInit } from '@angular/core';
import { Personnel201File, Personnel201Service, EmployeeDocument, getDocumentSrc } from '../personnel-201.service';
import { HttpClient } from '@angular/common/http';
import { ChangeDetectorRef } from '@angular/core';
export declare class DetailsAuditTrailModalComponent implements OnInit {
    private http;
    private personnelService;
    private cdr;
    file: Personnel201File | null;
    personnelId: string;
    close: EventEmitter<void>;
    closing: boolean;
    employeeDocuments: EmployeeDocument[];
    showImageModal: boolean;
    selectedImageDoc: EmployeeDocument | null;
    zoomLevel: number;
    panX: number;
    panY: number;
    isDragging: boolean;
    dragStartX: number;
    dragStartY: number;
    constructor(http: HttpClient, personnelService: Personnel201Service, cdr: ChangeDetectorRef);
    ngOnInit(): void;
    onClose(): void;
    getDocumentSrc: typeof getDocumentSrc;
    openDocument(doc: EmployeeDocument): void;
    openImageModal(doc: EmployeeDocument): void;
    closeImageModal(): void;
    zoomIn(): void;
    zoomOut(): void;
    resetZoom(): void;
    onImageMouseDown(event: MouseEvent): void;
    onImageMouseMove(event: MouseEvent): void;
    onImageMouseUp(): void;
    onImageMouseLeave(): void;
    onImageTouchStart(event: TouchEvent): void;
    onImageTouchMove(event: TouchEvent): void;
    onImageTouchEnd(): void;
    downloadAllAttachments(): Promise<void>;
    downloadSingleAttachment(doc: EmployeeDocument): void;
    viewSingleAttachment(doc: EmployeeDocument): void;
    formatFileSize(bytes: number): string;
}
//# sourceMappingURL=details-audit-trail-modal.component.d.ts.map