import { OnInit, OnDestroy } from '@angular/core';
import { FormBuilder, FormGroup } from '@angular/forms';
import { LeaveEmployeeService, LeaveType, LeaveBalance, LeaveApplication } from './leave-employee.service';
export declare class LeaveEmployeeComponent implements OnInit, OnDestroy {
    private leaveService;
    private fb;
    private destroy$;
    leaveTypes: LeaveType[];
    leaveBalances: LeaveBalance[];
    leaveApplications: LeaveApplication[];
    leaveForm: FormGroup;
    selectedLeaveType: LeaveType | null;
    selectedLeaveBalance: LeaveBalance | null;
    isLoading: boolean;
    isSubmitting: boolean;
    error: string | null;
    showApplyForm: boolean;
    showViewModal: boolean;
    showSuccessModal: boolean;
    selectedApplication: LeaveApplication | null;
    selectedFile: File | null;
    uploadedFileName: string | null;
    validationErrors: string[];
    formSubmitted: boolean;
    today: Date;
    totalLeaves: number;
    pendingLeaves: number;
    approvedLeaves: number;
    rejectedLeaves: number;
    totalDaysTaken: number;
    mostUsedType: string;
    toast: {
        show: boolean;
        title: string;
        message: string;
        type: string;
    } | null;
    toastTimeout: any;
    constructor(leaveService: LeaveEmployeeService, fb: FormBuilder);
    ngOnInit(): void;
    ngOnDestroy(): void;
    private loadInitialData;
    onApplyLeave(): void;
    onViewLeave(leave: LeaveApplication): void;
    onCancelLeave(leave: LeaveApplication): void;
    updateTotalDays(): void;
    onFileChange(event: any): void;
    validateForm(): boolean;
    submitForm(): void;
    resetForm(): void;
    getFileType(filename: string | undefined): string;
    getFileUrl(filename: string | undefined): string;
    showToast(title: string, message: string, type?: string, duration?: number): void;
    closeToast(): void;
    onLeaveTypeChange(leaveTypeId: string): void;
    calculateTotalDays(): void;
    updateMetrics(): void;
}
//# sourceMappingURL=leave-employee.component.d.ts.map